baseurl = "https://themes.gohugo.io/theme/hugo-theme-lean-launch-page/"
title = "Ronu"
author = "Ronu Laboratories, Inc"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

googleAnalytics = "UA-123456"

[params]
tagline = "Machine learning in only 2 steps."
mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"


